In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1 = {
    "name" : ["sayan","ram","sam","akash"],
    "Marks" : [45,44,32,23],
    "City" : ["kolkata", "howrah", "kolkata", "howrah"]
}

In [3]:
df = pd.DataFrame(dict1)

In [4]:
print(df)

    name  Marks     City
0  sayan     45  kolkata
1    ram     44   howrah
2    sam     32  kolkata
3  akash     23   howrah

In [6]:
ser = pd.Series(np.random.rand(34))

In [7]:
print(type(ser))

<class 'pandas.Series'>

In [8]:
data = pd.DataFrame(np.random.rand(334,5))

In [9]:
data

            0         1         2         3         4
0    0.029367  0.668463  0.634682  0.132486  0.647658
1    0.689269  0.586428  0.110552  0.740641  0.637260
2    0.635481  0.631226  0.586935  0.099123  0.470172
3    0.606280  0.642604  0.785369  0.013045  0.836834
4    0.502966  0.232170  0.767244  0.603994  0.412640
..        ...       ...       ...       ...       ...
329  0.651255  0.581010  0.440034  0.163287  0.139869
330  0.319404  0.661179  0.486116  0.930664  0.101767
331  0.365005  0.113509  0.162325  0.865495  0.422368
332  0.255601  0.105054  0.988847  0.582699  0.730982
333  0.196781  0.703320  0.132607  0.542967  0.193233

[334 rows x 5 columns]

In [10]:
type(data)

pandas.DataFrame

In [11]:
data.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.516355    0.502755    0.494845    0.498277    0.499838
std      0.292190    0.269062    0.288066    0.282314    0.293153
min      0.000689    0.000146    0.001576    0.006843    0.002424
25%      0.294318    0.284350    0.241509    0.267579    0.255833
50%      0.547052    0.503094    0.525043    0.466376    0.466478
75%      0.770396    0.709824    0.733511    0.740519    0.749440
max      0.996781    0.996741    0.998600    0.995399    0.988055

In [12]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 334 entries, 0 to 333
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       334 non-null    float64
 1   1       334 non-null    float64
 2   2       334 non-null    float64
 3   3       334 non-null    float64
 4   4       334 non-null    float64
dtypes: float64(5)
memory usage: 13.2 KB

In [14]:
data.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [17]:
data.index

RangeIndex(start=0, stop=334, step=1)

In [23]:
data.columns

RangeIndex(start=0, stop=5, step=1)

In [24]:
data.to_numpy()

array([[0.02936729, 0.66846311, 0.63468218, 0.13248605, 0.64765823],
       [0.68926901, 0.58642816, 0.11055241, 0.74064137, 0.63726041],
       [0.63548094, 0.63122573, 0.5869347 , 0.09912271, 0.47017151],
       ...,
       [0.36500527, 0.11350927, 0.16232487, 0.86549495, 0.42236753],
       [0.25560102, 0.10505405, 0.98884686, 0.5826986 , 0.73098234],
       [0.19678108, 0.70332   , 0.13260683, 0.54296712, 0.19323315]],
      shape=(334, 5))

In [25]:
data[0][0]= 0.3

C:\Users\sayan roy\AppData\Local\Temp\ipykernel_22752\1169712352.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  data[0][0]= 0.3

In [28]:
data.head()

          0         1         2         3         4
0  0.029367  0.668463  0.634682  0.132486  0.647658
1  0.689269  0.586428  0.110552  0.740641  0.637260
2  0.635481  0.631226  0.586935  0.099123  0.470172
3  0.606280  0.642604  0.785369  0.013045  0.836834
4  0.502966  0.232170  0.767244  0.603994  0.412640